#!/bin/bash

package_name="bash"
package_version="5.2.37"
package_address="http://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    sed --expression "0,/#endif/ s/#endif/#endif\n#include <unistd.h>/" \
        --in-place "$package_source/lib/termcap/tparam.c"

    "$package_source/configure"                                  \
        --docdir="/usr/share/doc/$package_name-$package_version" \
        --prefix="/usr"                                          \
        --with-installed-readline                                \
        --without-bash-malloc
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_directory" install
}
