#!/bin/bash

package_name="gawk"
package_version="5.3.1"
package_address="http://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    sed --in-place "s/extras//" "$package_source/Makefile.in"

    "$package_source/configure" --prefix="/usr"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_directory" install
}
