#!/bin/bash

package_name="make"
package_version="4.4.1"
package_address="http://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" --prefix="/usr"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_directory" install
}
